version: 2.1

executors:
  docker-executor:
    docker:
      - image: circleci/python:3.8

jobs:
  run-tests:
    executor: docker-executor
    environment:
      AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Set Environment Name
          command: |
            export ENVIRONMENT_NAME=dcapt-jira
      - run:
          name: RUN TESTS
          command: |
            docker run \
            -e AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID \
            -e AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY \
            -e REGION=us-east-2 \
            -e ENVIRONMENT_NAME=$ENVIRONMENT_NAME \
            -v "/$PWD:/data-center-terraform/dc-app-performance-toolkit" \
            -v "/$PWD/app/util/k8s/bzt_on_pod.sh:/data-center-terraform/bzt_on_pod.sh" \
            -it atlassianlabs/terraform:2.9.3 bash bzt_on_pod.sh jira.yml
      - persist_to_workspace:
          root: app/results
          paths:
            - '*'

workflows:
  version: 2
  test:
    jobs:
      - run-tests