version: 2.1

executors:
  docker-executor:
    docker:
      - image: docker:latest
      - image: circleci/python:3.11
    working_directory: ~/project

jobs:
  run-tests:
    executor: docker-executor
    environment:
      AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install JDK 17
          command: |
            sudo apt-get update
            sudo apt-get install -y openjdk-17-jdk
            java -version
      - run:
          name: Install Google Chrome and ChromeDriver
          command: |
            sudo apt-get update
            sudo apt-get install -y wget
            wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
            sudo apt-get install -y ./google-chrome-stable_current_amd64.deb
            CHROME_VERSION=$(google-chrome --version | grep -oP '\d+\.\d+\.\d+')
            CHROMEDRIVER_VERSION=$(wget -qO- https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION)
            wget https://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip
            unzip chromedriver_linux64.zip
            sudo mv chromedriver /usr/local/bin/
            chromedriver --version
      - run:
          name: Setup Python Virtual Environment
          command: |
            python3 --version
            pip install virtualenv
            virtualenv venv -p python3
            source venv/bin/activate
            pip install -r requirements.txt
      - run:
          name: Verify Host File
          command: |
            echo "Current Directory: $(pwd)"
            ls -l "$(pwd)/app/util/k8s/bzt_on_pod.sh"
      - run:
          name: Set Environment Name
          command: |
            export ENVIRONMENT_NAME=dcapt-jira
      - run:
          name: Verify Docker Version
          command: docker --version
      - run:
          name: Verify bzt_on_pod.sh Exists
          command: |
            ls -l "$(pwd)/app/util/k8s/bzt_on_pod.sh"
      - run:
          name: Set Executable Permissions
          command: chmod +x "$(pwd)/app/util/k8s/bzt_on_pod.sh"
      - run:
          name: RUN TESTS
          command: |
            docker run \
            -e AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID \
            -e AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY \
            -e REGION=us-east-2 \
            -e ENVIRONMENT_NAME=$ENVIRONMENT_NAME \
            -v "$(pwd):/data-center-terraform/dc-app-performance-toolkit" \
            -v "$(pwd)/app/util/k8s/bzt_on_pod.sh:/tmp/run_bzt.sh:ro" \
            -it atlassianlabs/terraform:2.9.3 bash /tmp/run_bzt.sh jira.yml
      - persist_to_workspace:
          root: app/results
          paths:
            - '*'

workflows:
  version: 2
  test:
    jobs:
      - run-tests